add rsync cmds

diff --git a/configs/shared/overlay-livecd/etc/manjaro/functions b/configs/shared/overlay-livecd/etc/manjaro/functions
--- a/configs/shared/overlay-livecd/etc/manjaro/functions
+++ b/configs/shared/overlay-livecd/etc/manjaro/functions
@@ -632,6 +632,37 @@ run_unsquashfs()
     mv "/tmp/unsquashfs.log" "/tmp/unsquashfs-$SQF_FILE.log"
 }
 
+# run_mount_sqf()
+# runs mount on SQF_FILE
+run_mount_sqf()
+{
+    # mount SQF_FILE to RSYNC_SOURCE
+    mount ${SQF_FILE} ${RSYNC_SOURCE} -t squashfs -o loop
+}
+
+# run_umount_sqf()
+# runs umount on SQF_FILE
+run_umount_sqf()
+{
+    # umount SQF_FILE from RSYNC_SOURCE
+    umount ${RSYNC_SOURCE}
+}
+
+# run_rsync()
+# runs rsync on the target system, displays output
+#
+run_rsync()
+{
+    # all rsync output goes to /tmp/rsync.log, which we tail
+    rsync -av --progress ${RSYNC_SOURCE}/* ${RSYNC_TARGET} | \
+    awk -f rsync.awk | \
+    sed -u 's/\([0-9]*\).*/\1/' | \
+    DIALOG --title "$_unsquash_dialog_title" --gauge "$_unsquash_dialog_info1 $SQF_FILE $_unsquash_dialog_info2" 10 60 0
+
+    # save rsync.log
+    #mv "/tmp/rsync.log" "/tmp/rsync-$SQF_FILE.log"
+}
+
 # run_mkinitcpio()
 # runs mkinitcpio on the target system, displays output
 #
@@ -671,9 +702,9 @@ printk()
     esac
 }
 
-# installsystem()
+# installsystem_unsquash()
 # installs to the target folder
-installsystem() {
+installsystem_unsquash() {
     DIALOG --msgbox "${_installationwillstart}" 0 0
     clear
     mkdir -p ${DESTDIR}
@@ -746,6 +777,113 @@ installsystem() {
 
     DIALOG --title "$_result" --exit-label "${_continue_label}" \
         --textbox "/tmp/unsquasherror.log" 18 60 || return 1
+
+    # ensure the disk is synced
+    sync
+
+    S_INSTALL=1
+    NEXTITEM=4
+
+    # automagic time!
+    # any automatic configuration should go here
+    DIALOG --infobox "${_configuringsystem}" 6 40
+    sleep 3
+
+    hd_config
+    auto_fstab
+    _system_is_installed=1
+}
+
+# installsystem_rsync()
+# installs to the target folder
+installsystem_rsync() {
+    DIALOG --msgbox "${_installationwillstart}" 0 0
+    clear
+    mkdir -p ${DESTDIR}
+    #rsync -av --progress /source/root-image ${DESTDIR}
+    RSYNC_SOURCE=/source/root-image
+    mkdir -p ${RSYNC_SOURCE}
+    RSYNC_TARGET=${DESTDIR}
+    SQF_FILE=root-image.sqfs
+    run_mount_sqf
+    run_rsync
+    run_umount_sqf
+    echo $? > /tmp/.install-retcode
+    if [ $(cat /tmp/.install-retcode) -ne 0 ]; then echo -e "\n${_installationfail}" >>/tmp/rsyncerror.log
+    else echo -e "\n => Root-Image: ${_installationsuccess}" >>/tmp/rsyncerror.log
+    fi
+
+    if [ -e "/bootmnt/manjaro/${arch}/xfce-image.sqfs" ] ; then
+       #rsync -av --progress /source/xfce-image ${DESTDIR}
+       RSYNC_SOURCE=/source/xfce-image
+       mkdir -p ${RSYNC_SOURCE}
+       RSYNC_TARGET=${DESTDIR}
+       SQF_FILE=xfce-image.sqfs
+       run_mount_sqf
+       run_rsync
+       run_umount_sqf
+       echo $? > /tmp/.install-retcode
+       if [ $(cat /tmp/.install-retcode) -ne 0 ]; then echo -e "\n${_installationfail}" >>/tmp/rsyncerror.log
+       else echo -e "\n => XFCE-Image: ${_installationsuccess}" >>/tmp/rsyncerror.log
+       fi
+    fi
+
+    if [ -e "/bootmnt/manjaro/${arch}/kde-image.sqfs" ] ; then
+       #rsync -av --progress /source/kde-image ${DESTDIR}
+       RSYNC_SOURCE=/source/kde-image
+       mkdir -p ${RSYNC_SOURCE}
+       RSYNC_TARGET=${DESTDIR}
+       SQF_FILE=kde-image.sqfs
+       run_mount_sqf
+       run_rsync
+       run_umount_sqf
+       echo $? > /tmp/.install-retcode
+       if [ $(cat /tmp/.install-retcode) -ne 0 ]; then echo -e "\n${_installationfail}" >>/tmp/rsyncerror.log
+       else echo -e "\n => KDE-Image: ${_installationsuccess}" >>/tmp/rsyncerror.log
+       fi
+    fi
+
+    if [ -e "/bootmnt/manjaro/${arch}/gnome-image.sqfs" ] ; then
+       #rsync -av --progress /source/gnome-image ${DESTDIR}
+       RSYNC_SOURCE=/source/gnome-image
+       mkdir -p ${RSYNC_SOURCE}
+       RSYNC_TARGET=${DESTDIR}
+       SQF_FILE=gnome-image.sqfs
+       run_mount_sqf
+       run_rsync
+       run_umount_sqf
+       echo $? > /tmp/.install-retcode
+       if [ $(cat /tmp/.install-retcode) -ne 0 ]; then echo -e "\n${_installationfail}" >>/tmp/rsyncerror.log
+       else echo -e "\n => Gnome-Image: ${_installationsuccess}" >>/tmp/rsyncerror.log
+       fi
+    fi
+
+    if [ -e "/bootmnt/manjaro/${arch}/openbox-image.sqfs" ] ; then
+       #rsync -av --progress /source/openbox-image ${DESTDIR}
+       RSYNC_SOURCE=/source/openbox-image
+       mkdir -p ${RSYNC_SOURCE}
+       RSYNC_TARGET=${DESTDIR}
+       SQF_FILE=openbox-image.sqfs
+       run_mount_sqf
+       run_rsync
+       run_umount_sqf
+       echo $? > /tmp/.install-retcode
+       if [ $(cat /tmp/.install-retcode) -ne 0 ]; then echo -e "\n${_installationfail}" >>/tmp/rsyncerror.log
+       else echo -e "\n => Openbox-Image: ${_installationsuccess}" >>/tmp/rsyncerror.log
+       fi
+    fi
+
+    # finished, display scrollable output
+    local _result=''
+    if [ $(cat /tmp/.install-retcode) -ne 0 ]; then
+      _result="${_installationfail}"
+    else
+      _result="${_installationsuccess}"
+    fi
+    rm /tmp/.install-retcode
+
+    DIALOG --title "$_result" --exit-label "${_continue_label}" \
+        --textbox "/tmp/rsyncerror.log" 18 60 || return 1
 
     # ensure the disk is synced
     sync
