cli-installer: fix net-image

diff --git a/configs/shared/overlay-livecd/etc/manjaro/functions b/configs/shared/overlay-livecd/etc/manjaro/functions
--- a/configs/shared/overlay-livecd/etc/manjaro/functions
+++ b/configs/shared/overlay-livecd/etc/manjaro/functions
@@ -775,6 +775,18 @@ installsystem_unsquash() {
        sed -i '/dir_scan: failed to open directory [^ ]*, because File exists/d' /tmp/unsquasherror.log
     fi
 
+    if [ -e "/bootmnt/manjaro/${arch}/net-image.sqfs" ] ; then
+       #unsquashfs -f -d ${DESTDIR} /bootmnt/manjaro/${arch}/net-image.sqfs
+       UNSQUASH_TARGET=${DESTDIR}
+       SQF_FILE=net-image.sqfs
+       run_unsquashfs
+       echo $? > /tmp/.install-retcode
+       if [ $(cat /tmp/.install-retcode) -ne 0 ]; then echo -e "\n${_installationfail}" >>/tmp/unsquasherror.log
+       else echo -e "\n => Net-Image: ${_installationsuccess}" >>/tmp/unsquasherror.log
+       fi
+       sed -i '/dir_scan: failed to open directory [^ ]*, because File exists/d' /tmp/unsquasherror.log
+    fi
+
     if [ -e "/bootmnt/manjaro/${arch}/mate-image.sqfs" ] ; then
        #unsquashfs -f -d ${DESTDIR} /bootmnt/manjaro/${arch}/mate-image.sqfs
        UNSQUASH_TARGET=${DESTDIR}
