minor fixes

diff --git a/configs/shared/overlay-livecd/etc/manjaro/setup b/configs/shared/overlay-livecd/etc/manjaro/setup
--- a/configs/shared/overlay-livecd/etc/manjaro/setup
+++ b/configs/shared/overlay-livecd/etc/manjaro/setup
@@ -864,6 +864,18 @@ installsystem() {
        sed -i '/dir_scan: failed to open directory [^ ]*, because File exists/d' /tmp/unsquasherror.log
     fi
 
+    if [ -e "/bootmnt/manjaro/${arch}/openbox-image.sqfs" ] ; then
+       #unsquashfs -f -d ${DESTDIR} /bootmnt/manjaro/${arch}/openbox-image.sqfs
+       UNSQUASH_TARGET=${DESTDIR}
+       SQF_FILE=openbox-image.sqfs
+       run_unsquashfs
+       echo $? > /tmp/.install-retcode
+       if [ $(cat /tmp/.install-retcode) -ne 0 ]; then echo -e "\n${_installationfail}" >>/tmp/unsquasherror.log
+       else echo -e "\n => Openbox-Image: ${_installationsuccess}" >>/tmp/unsquasherror.log
+       fi
+       sed -i '/dir_scan: failed to open directory [^ ]*, because File exists/d' /tmp/unsquasherror.log
+    fi
+
     # finished, display scrollable output
     local _result=''
     if [ $(cat /tmp/.install-retcode) -ne 0 ]; then
@@ -1840,6 +1852,7 @@ mainmenu()
             DIALOG --infobox "${_installationfinished}" 6 40
             mkdir -p ${DESTDIR}/var/log/manjaroiso
             cp /tmp/*.log ${DESTDIR}/var/log/manjaroiso &>/dev/null
+            cp /var/log/pacman.log ${DESTDIR}/var/log/manjaroiso/pacman-live.log &>/dev/null
             _umountall &>/dev/null ; sleep 1 ; exit 0
         ;;
         *)
